#!/usr/bin/bash

l=()

for x in $(ls $HOME/Imágenes/wallpapers/)
do
  if [ $x != 'salvar' ]
  then
    l+=("$x")
    echo $x
  fi
done

while IFS= read -r line
do
  nro="$line"
done < /opt/scripts/nro_wall


if [ $nro -eq ${#l[@]} ]
then
  echo "1" > /opt/scripts/nro_wall
else
  echo $((nro+1)) > /opt/scripts/nro_wall
fi

wall="$HOME/Imágenes/wallpapers/${l[$nro]}"

feh --bg-fill $wall
