#!/usr/bin/bash

l=()

for x in $(ls /usr/share/backgrounds/wanderos/)
do
  l+=("$x")
done

while IFS= read -r line
do
  nro="$line"
done < /opt/script/nro_wall


if [ $nro -eq ${#l[@]} ]
then
  echo "1" > /opt/script/nro_wall
else
  echo $((nro+1)) > /opt/script/nro_wall
fi

wall="/usr/share/backgrounds/wanderos/${l[$nro]}"

feh --bg-fill $wall
