#!/bin/bash
# 
# Script para realizar consultas a mistral usando el API KEY gratuito
#

if [ $# -eq 0 ]; then
  echo "Error: Debes proporcionar un prompt como argumento"
  echo "Ejemplo: ./consulta 'mi pregunta'"
  exit 1
fi

       #"model": "mistral-tiny",
USER_PROMPT="$*"

RESPONSE=$(curl -sS -X POST "https://api.mistral.ai/v1/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $MISTRAL_API_KEY" \
  -d '{
       "model": "mistral-small-latest",
       "messages": [{"role": "user", "content": "'"$USER_PROMPT"'"}],
       "temperature": 0.7
      }')

if [ $? -ne 0 ]; then
  echo "Error en la solicitud a la API"
  exit 1
fi

echo "$RESPONSE" | jq -r '.choices[0].message.content'
